# Generated by Django 5.2.4 on 2025-08-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='robust',
            field=models.IntegerField(default=0),
        ),
    ]
