# Generated by Django 5.2.4 on 2025-08-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_player_robust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='robust',
            new_name='matches',
        ),
    ]
